### ISSUE TITLE
明明设置了 advconfig 还是让填写配置

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#130]
```
shell: /bin/bash -e ***0***
env:
  ADVCONFIG: ***
  BILICONFIG: 
  PUSH_MESSAGE: 
##[endgroup***
Traceback (most recent call last):
  File "secrets2config.py", line 21, in <module>
    configData: dict = json.loads(re.sub(r'\/\*[\s\S****?\*\/', '', fp.read()), object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 49 column 9 (char 1098)
##[error***Process completed with exit code 1.
```

**Comment by happy888888** [comment]
格式错了，检查一下引号，逗号，括号是否符合json规范

**Comment by if1y** [comment]
已解决～
