### ISSUE TITLE
作者您好，漫画下载碰到标题里有特殊字符的会报错。

### ISSUE THREAD

**Issue by rewag01** [happy888888/BiliExp#138]
win10下用BiliExp-v1.1.8下载漫画，碰到抓取的标题里含有无法用于建立文件夹的特殊字符就会报错，麻烦修复下，感谢。

**Comment by happy888888** [comment]
比如什么字符，麻烦发一下漫画例子

**Comment by rewag01** [comment]
您好，比如mc26731，漫画《在魔王城说晚安》的第86话，里面有&lt <>这样的，WINDOWS系统不能用于创建文件夹的字符，似乎都会报错。同漫画148话的斜杠、反斜杠那类的也会。

**Comment by happy888888** [comment]
已尝试修复，但由于我的账号没有解锁漫画无法测试，可尝试直接下载最新代码运行或者win(exe)测试修复版本[mangaDownloader.exe 1.18 bug-fix-test](http://d0.ananas.chaoxing.com/download/742ec257a86d88f86afd548e1901a829)看是否成功修复，此问题将在下个release版本得到完整解决

**Comment by rewag01** [comment]
您好，我测试了一下，似乎还是不行。

开始下载漫画 "在魔王城说晚安"
Traceback (most recent call last):
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 138, in <module>
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 107, in main
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 83, in download_task
  File "BiliClient\Manga.py", line 61, in download
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: './在魔王城说晚安/086-被褥<朋友>（跟踪狂）'
[19416] Failed to execute script mangaDownloader

开始下载漫画 "在魔王城说晚安"
Traceback (most recent call last):
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 138, in <module>
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 107, in main
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 83, in download_task
  File "BiliClient\Manga.py", line 61, in download
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'E:\\download\\comic/在魔王城说晚安/148-2%是1/50对吧？'
[19584] Failed to execute script mangaDownloader

**Comment by happy888888** [comment]
[mangaDownloader.exe 1.1.8 bug-fix-test2](http://d0.ananas.chaoxing.com/download/e96135a13b28977eb5add8468034158f)

**Comment by rewag01** [comment]
您好，使用mangaDownloader.exe 1.1.8 bug-fix-test2已经可以正常下载了，谢谢。
