### ISSUE TITLE
更新代码后运行报错，配置已同步更新

### ISSUE THREAD

**Issue by if1y** [happy888888/BiliExp#141]
**manga_comrade_task 的配置已经去除……**

```
Traceback (most recent call last):
  File "BiliExp.py", line 6, in <module>
    import tasks
  File "/home/runner/work/BiliExp_Actions/BiliExp_Actions/tasks/__init__.py", line 10, in <module>
    from .manga_comrade_task import manga_comrade_task as manga_comrade_task
ModuleNotFoundError: No module named 'tasks.manga_comrade_task'
##[error***Process completed with exit code 1.
```

**Comment by if1y** [comment]
看起来是这里没有移除

https://github.com/happy888888/BiliExp/blob/c07b412887a9ea84916e7998f9ef6d82f7422e4b/tasks/__init__.py#L10

**Comment by happy888888** [comment]
已删除，删除这一排就好了

**Comment by if1y** [comment]
嗯嗯，就是报告一下😉
