### ISSUE TITLE
部署时400错误

### ISSUE THREAD

**Issue by ykrank** [happy888888/BiliExp#184]
```
Action: "deploy" - Stage: "dev" - App: "bilibili" - Instance: "BiliExp"
Uploading...

 Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/serverless/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by ykrank** [comment]
腾讯云部署

**Comment by happy888888** [comment]
可能云函数那边抽风了，重试一下

**Comment by ykrank** [comment]
的确如此，已经好了
