### ISSUE TITLE
互动抽奖转发失败

### ISSUE THREAD

**Issue by windCloud152** [happy888888/BiliExp#225]
互动抽奖我设置强制关注抽奖号转发，更新后发现转发失败，提示出错，请问该怎么解决
```
控制台提示：
                  future: <Task finished coro=<lottery_task() done, defined at /home/runner/work/BiliExp/BiliExp/tasks/lottery_task.py:11> exception=NameError("name 'uname' is not defined",)>
                  Traceback (most recent call last):
                  File "/home/runner/work/BiliExp/BiliExp/tasks/lottery_task.py", line 22, in lottery_task
                  await repost_task_E(biliapi, task_config, start_time, end_time)
                  File "/home/runner/work/BiliExp/BiliExp/tasks/lottery_task.py", line 166, in repost_task_E
                  if await dynamicReply(biliapi, dyid, oid, reply, type, uname):
                  NameError: name 'uname' is not defined
                  [ERROR***: Task exception was never retrieved
```
```
配置文件：
"lottery_task": {         // 任务:动态抽奖转发评论点赞
            "enable": true,     
            "reply": ["支持支持[tv_点赞]"],  
            "repost": ["支持支持[tv_点赞]"],                                                
            "keywords": ["^((?!恭喜).)*#互动抽奖#((?!恭喜).)*$", "^((?!恭喜).)*#抽奖#((?!恭喜).)*$", ".*(转|抽|评).*(转|抽|评).*(转|抽|评).*"],
            "repost_with_tag": {    
                "fix": 1,  
                "except": ["抽奖"],
                "reply_with_tag": false 
            }, 
            "time_quantum": [-43200,43200],
            "delay": [15, 30], 
            "repost_by_others": [uid],
            "force_follow": true   
        }
```

**Comment by yun-Tong** [comment]
环境Actions

**Comment by windCloud152** [comment]
使用actions环境
```
经过测试
	手动互动转发正常
	代码转发抽奖正常
        配置没有其他错误
```
```
出错点：
	强制跟踪转发
	"repost_by_others": [uid]
	开启会出现上述错误
	更换不同uid结果相同
```

**Comment by happy888888** [comment]
已尝试修复此问题，请使用最新的代码

**Comment by windCloud152** [comment]
经测试，此问题已修复
