### ISSUE TITLE
机器人up主报错

### ISSUE THREAD

**Issue by 2595133804** [happy888888/BiliExp#26]
[root@server up]# python pic.py 
  File "pic.py", line 29
    url = f"https://www.pixiv.net/artworks/{id}"
                                               ^
SyntaxError: invalid syntax

**Comment by happy888888** [comment]
请使用python3.6及以上版本

python3 pic.py

**Comment by happy888888** [comment]
同时安装python2和python3必须指定用python3调用文件
注意运行目录是在项目的根目录而不是文件所在目录，先cd到/BiliExp文件夹下，否则会出现找不到"models"的问题

**Comment by 2595133804** [comment]
如何在根目录调用文件呢

**Comment by 2595133804** [comment]
[root@server BiliExp]# python3 ./pic.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f75a27344e0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.pixiv.net', port=443): Max retries exceeded with url: /ajax/top/illust?mode=all&lang=zh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75a27344e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pic.py", line 23, in <module>
    content = session.get("https://www.pixiv.net/ajax/top/illust?mode=all&lang=zh", headers=headers)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.pixiv.net', port=443): Max retries exceeded with url: /ajax/top/illust?mode=all&lang=zh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75a27344e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by 2595133804** [comment]
[root@server BiliExp]# python3 ./pic.py
Traceback (most recent call last):
  File "./pic.py", line 25, in <module>
    list = jsobj["body"]["thumbnails"]["illust"]
TypeError: list indices must be integers or slices, not str

**Comment by happy888888** [comment]
你有www.pixiv.net账号吗，目前没有账号并不允许访问P站，就会报错，代码第20行

PHPSESSID=52458727_sAt5kuqMf4cHifp7uVHYA8PzfUcSFhK0

需要改成你P站账号登录后的cookie才行，改写"PHPSESSID="后面的部分，因为默认使用的我原来的p站账号现在登录状态过期了

**Comment by happy888888** [comment]
cookie获取方式与B站类似，都是先登录后用F12打开控制台，不过需要找的是PHPSESSID这个参数

**Comment by 2595133804** [comment]
现在脚本正常了，但是投稿接口有问题？
b站后台看不到投稿记录

**Comment by happy888888** [comment]
草稿箱也没有吗

**Comment by 2595133804** [comment]
> 草稿箱也没有吗

没有

**Comment by happy888888** [comment]
你是否在config.json文件里写了你的B站登录cookie

**Comment by 2595133804** [comment]
> 你是否在config.json文件里写了你的B站登录cookie

确认过了。。是的

**Comment by happy888888** [comment]
你试试把最后一行的的注释取消呢，去掉前面的#号，我这里测试没问题啊，还是用的国外的vps

**Comment by 2595133804** [comment]
那个草稿箱是不是只有手机有

**Comment by happy888888** [comment]
电脑也有
![image](https://user-images.githubusercontent.com/67217225/94697123-658ba780-036a-11eb-9d90-606f373a1ec6.png)

**Comment by 2595133804** [comment]
找到了，谢谢

**Comment by 2595133804** [comment]
[root@server BiliExp]# python3 ./ytb.py
Traceback (most recent call last):
  File "./ytb.py", line 2, in <module>
    from models.Video import Video
ImportError: cannot import name 'Video' from 'models.Video' (/root/BiliExp/models/Video.py)

**Comment by happy888888** [comment]
这确实是我疏忽了后面做视频下载的时候把类名字改了......
第二行改为 from models.Video import VideoUploader
第24行改为 bilivideo = VideoUploader(configData["cookieDatas"][0])

**Comment by 2595133804** [comment]
[root@server BiliExp]# python3 ./ytb.py
Traceback (most recent call last):
  File "./ytb.py", line 4, in <module>
    from pytube import YouTube
  File "/usr/local/lib/python3.7/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/usr/local/lib/python3.7/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/usr/local/lib/python3.7/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (/usr/local/lib/python3.7/site-packages/pytube/compat.py)

**Comment by happy888888** [comment]
这是pytube的问题，估计是版本太老了，你可以试试安装pytube3

**Comment by 2595133804** [comment]
可以了~

**Comment by happy888888** [comment]
这玩意儿被放弃的根本原因是B站没给海外接口，国外vps上传速度超超超级慢，很鸡肋

**Comment by 2595133804** [comment]
我腾讯轻量上传100-200k，是很慢。。

**Comment by 2595133804** [comment]
我在想，是不是可以搭建回国跳板，哈哈
