### ISSUE TITLE
漫画下载器错误

### ISSUE THREAD

**Issue by startingdawn2** [happy888888/BiliExp#276]
遇到没有购买的章节会直接报错，不能跳过（之前的版本会弹出，“需要购买”，并继续下载接下来的章节）

报错如下：

Traceback (most recent call last):
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 164, in <module>
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 133, in main
  File "G:\Users\Timtian\source\repos\bili\release\mangaDownloader.py", line 77, in download_task
  File "BiliClient\Manga.py", line 157, in downloadIndexes
NameError: name 'x' is not defined

**Comment by happy888888** [comment]
已解决，请重新下载

**Comment by startingdawn2** [comment]
好的，谢谢大佬。

顺便问一下，APP登录令牌跟APP刷新令牌是什么鬼？（虽然不用用到）

**Comment by happy888888** [comment]
账号密码登录成功后，就会获得APP登录令牌和APP刷新令牌，有APP登录令牌就相当于登录了B站app，用APP刷新令牌和APP登录令牌可以获得新的APP刷新令牌和APP登录令牌和cookie(SESSDATA和bili_jct)(旧的令牌和cookie立即失效，所以叫刷新)，有SESSDATA就相当于登录了B站网页，有bili_jct才能使用网页的点赞，投币等功能

**Comment by startingdawn2** [comment]
哦，明白了，原来是这样，谢谢大佬。

有个疑问，之前我记得bilibili网页端看漫画是可以跟APP一样调画质的清晰度的
请问下载漫画时，用APP端接口跟网页端接口下载的漫画清晰度是一样的吗？有区别吗？
