### ISSUE TITLE
wasmtime有32位的软件吗，树莓派系统不是64位的

### ISSUE THREAD

**Issue by tlj218** [happy888888/BiliExp#352]
因为树莓派系统不是64位的，所以最新版本无法运行，请问哪位大佬知道wasmtime哪个版本是支持32位系统的。
Traceback (most recent call last):
  File "BiliExp.py", line 7, in <module>
    from BiliClient import asyncbili
  File "/home/pi/BiliExp/BiliClient/__init__.py", line 12, in <module>
    from .asyncBiliApi import asyncBiliApi as asyncbili #B站接口模块，由aiohttp模块实现异步http请求
  File "/home/pi/BiliExp/BiliClient/asyncBiliApi.py", line 9, in <module>
    from .wasm_enc import calc_sign
  File "/home/pi/BiliExp/BiliClient/wasm_enc/__init__.py", line 1, in <module>
    from .spyder import calc_sign
  File "/home/pi/BiliExp/BiliClient/wasm_enc/spyder.py", line 3, in <module>
    from .rustwasm import RustWasm
  File "/home/pi/BiliExp/BiliClient/wasm_enc/rustwasm.py", line 5, in <module>
    from wasmtime import Store, Module, Instance
  File "/usr/local/lib/python3.7/dist-packages/wasmtime/__init__.py", line 17, in <module>
    from ._config import Config
  File "/usr/local/lib/python3.7/dist-packages/wasmtime/_config.py", line 1, in <module>
    from . import _ffi as ffi
  File "/usr/local/lib/python3.7/dist-packages/wasmtime/_ffi.py", line 10, in <module>
    raise WasmtimeError("wasmtime only works on 64-bit platforms right now")
wasmtime._error.WasmtimeError: **wasmtime only works on 64-bit platforms right now**

**Comment by happy888888** [comment]
删除`BiliClient/wasm_enc`文件夹

**Comment by tlj218** [comment]
谢谢，已经成功

**Comment by ahuihui** [comment]
B站能下载无水印的视频吗
