### ISSUE TITLE
非大会员账号执行大会员任务报错

### ISSUE THREAD

**Issue by wangmanv2** [happy888888/BiliExp#405]
非大会员账号执行大会员任务报错
```
Error: 4-20 20:05:11,118] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-6' coro=<vip_task() done, defined at /home/runner/work/BiliExp/BiliExp/tasks/vip_task.py:8> exception=KeyError('code')>
Traceback (most recent call last):
  File "/home/runner/work/BiliExp/BiliExp/tasks/vip_task.py", line 22, in vip_task
    await bpCharge(biliapi, task_config["BpCharge"])
  File "/home/runner/work/BiliExp/BiliExp/tasks/vip_task.py", line 92, in bpCharge
    if ret["code"] != 0:
KeyError: 'code'
```

**Comment by wangmanv2** [comment]
版本 1.2.1
运行环境 Actions
去除大会员相关任务则无报错

**Comment by Dark-Metal** [comment]
```python
    if ret["errno"] != 0:
        logging.warning(f'{biliapi.name}: 获取B币劵数量失败，信息为{ret["message"]}，跳过消费')
        return

    cbp = ret["data"]["couponBalance"]
    for x in chargeConfig:
        if cbp < 1:
            break
        if chargeConfig[x] < 1:
            continue
        pay = cbp if chargeConfig[x] > cbp else chargeConfig[x]
```
vip_task.py line 92 修改后才可正常充电

**Comment by wangliv2** [comment]
感谢，其实只用修改92行的变成`if ret["errno"] != 0:`就好了吧，下面虽然重复使用减少了内存损耗，但是感觉问题也不大的样子。
