### ISSUE TITLE
填写advconfig后获取用户信息报错

### ISSUE THREAD

**Issue by 2595133804** [happy888888/BiliExp#78]
##[group***Run python3 secrets2config.py
python3 secrets2config.py
shell: /bin/bash -e ***0***
env:
  ADVCONFIG: ***
  BILICONFIG: ***
  PUSH_MESSAGE: ***
##[endgroup***
Traceback (most recent call last):
  File "secrets2config.py", line 21, in <module>
    configData: dict = json.loads(re.sub(r'\/\*[\s\S****?\/', '', fp.read()), object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 25 column 9 (char 487)
##[error***Process completed with exit code 1.

**Comment by happy888888** [comment]
应该是有的字段名称没有用双引号括起来
